### ISSUE TITLE
How do I assign keyboard shortcuts to start/stop screen recording?

### ISSUE THREAD

**Issue by kandadaboggu** [rjanja/desktop-capture#30]
I didn't find any options in the configuration screens.

**Comment by rjanja** [comment]
I've added this feature in for #32 - it works slightly differently depending on whether you're using the built-in recorder (starts/stops) or custom recorder e.g. FFmpeg (only stops). I'm not modifying the Cinnamon shortcut but providing an applet-specific one. Let me know if you run into any problems with it. The updated applet is version 1.01 and available on Spices or direct from Github. Thanks, and cheers!
