### ISSUE TITLE
Support using Kazam

### ISSUE THREAD

**Issue by isleshocky77** [rjanja/desktop-capture#36]
It would be nice to support using Kazam as a Screencast and Screenshot program.

https://launchpad.net/kazam

**Comment by rjanja** [comment]
Hi, thanks for the feedback. I've looked at Kazam in the past but just installed it and there are limited options for controlling it from this applet. I can still add some basic support if desired, but I'm more interested in why you'd like to use this applet with it or what you like most about Kazam.

Thanks!

**Comment by isleshocky77** [comment]
I would prefer just using Cinnamon Recorder so I didn't have to install anything extra; however, it is segfaulting for me and I didn't have time to track down why or how to fix it.  I tried the other recorders which you integrate and none of them seemed to work as well as Kazam

**Comment by rjanja** [comment]
Thanks @isleshocky77 I appreciate the feedback. Sorry that C-R is not working, it's part of Cinnamon so the only recommendation I can make there is to verify/reset your gstreamer pipeline. You can do this by running `dconf-editor`, then finding the `pipeline` key in org.cinnamon.recorder. If it's not blank, you could try blanking it out. If after restarting Cinnamon (save your docs, then Alt+F2, 'r', enter, or simply log out/in) that doesn't work then it's possible there's one or two gstreamer-related libraries that are corrupt, conflicting or not installed. Did it ever work for you?

I've been working on and off (slowly) on adding better support for recorders, including hotkeys and window selection. I don't use C-R much these days. I'll make sure to include Kazam support in the next update, but in so far as recording goes, it'll really only be able to trigger the Kazam UI to show up and not specify any recording configuration.

**Comment by rjanja** [comment]
Kazam support added in 0f62aa98cb528be1ec7f42e958d3b01190bd34b1
