### ISSUE TITLE
Add a 'Repeat Last' button/hotkey option to the menu

### ISSUE THREAD

**Issue by crydalch** [rjanja/desktop-capture#37]
This is hands down, the most useful applet for taking screen-shots that I've ever used. Nothing else compares, you've really done a fantastic job!

One feature that would make it even better is a **Repeat Last** command, where it would let you re-do taking a screenshot of the last area/region or window (including the timer countown), as if you'd clicked it again. The biggest use case I'd love it for, is comparisons for bug reports or teaching purposes.

For example: I want to demonstrate a bug that happens on a menu item, so I draw a box around the area where the menu will be, hit enter, click the menu to highlight, and the screenshot is taken. But then to take a screenshot of that exact same thing, except with some other setting that makes a menu disapper, I have to just eyball it, and edit the picture later.

Would it be possible to add a repeat last screenshot command to the menu? And the ability to add a hotkey would be great too.

This also makes me wondering how hard it'd be to have "bookmarks" where either a region of the screen or a window id are bookmarked, and all we have to do is click, and after the countdown the screenshot will trigger.

Again, can't tell you enough how useful this thing is!

Thanks!

**Comment by rjanja** [comment]
Hi @crydalch, thanks for your feedback. Hands down the most positive comments received :-).

The *Repeat Last* feature you mention is already implemented when using the built-in capture tool, except it is named *Redo* in the menu. After considering it, I think "redo" is a bit of a misnomer, as it doesn't replace the last capture, but takes a new one with the same parameters. So I will proceed with changing the menu item to "Repeat Last" per your suggestion. Could you confirm whether you are using the built-in capture mode, or a different capture program? In the case of the latter, it may be more difficult (but perhaps not impossible) to implement.

With regards to the hotkey support, this would be an easy feature to add. I will proceed with using this ticket for the renaming of menu item and the adding of hotkey, and will have an update today.

While I like the idea of bookmarks or repeatable capture history, the caveat here is that window IDs may no longer exist when attempting to recall these parameters. This'll require some more thought, and perhaps only recalling the capture area and dimensions as opposed to a specific window. I'll create a separate ticket to track that.

I'm glad you're enjoying the applet. Thanks again for the feedback!

**Comment by crydalch** [comment]
Yep, nearly everything I've wanted in a screenshot/recording tool either already exists, or is being talked about in these comments :) If only the cinnamon-recorder were 

Oh my gosh, I can't believe I didn't see *Redo Last* right there in the menu! Yes, I'm using Cinnamon Screenshot, so this is perfect. I think giving it the new label, and a hotkey, would be super cool! Thanks @rjanja ! 

How cumbersome would it be to support these features for the video recordings? I imagine (in my head), maybe the applet would just remember the last screen dimensions, and pass those to the recording command if **Repeat Last** is invoked for the video?

Regarding the bookmarks, yeah Window IDs would be cool, that's probably too ambitious. Just being able to bookmark the region on the screen, would be amazing!

Thank you!

**Comment by rjanja** [comment]
@crydalch I've bumped the version to 1.02 with the Repeat Last hotkey support. Give it a try and let me know if you have any troubles.

Re: recorder support, I have a work in progress (unpublished) for redoing the custom recorder commands, mainly to make it possible to have different toggle switches and controls per recorder program instead of trying to fit them all into a single scheme. The recording-in-progress is currently broken but once it's working again it shouldn't be too difficult to have a similar "Repeat Last" there.

**Comment by crydalch** [comment]
You're too fast @rjanja! Okay, I updated, and interestingly, the *Redo Last/Repeat Last* option has disappeared from the menu. I do see the new hot-key, and that works great! Was the menu removal on purpose, because of the hotkey? Even though the menu is starting to get long, I feel that others more observant than myself might discover the feature more quickly if it's there.

Great news about the recorder, thanks!

**Comment by crydalch** [comment]
Okay spooky - it's there now. I should have taken a screenshot, because now I'm worried I've lost my mind. Yeesh... 

Thanks @rjanja stellar job!
