### ISSUE TITLE
Hotkey as Tooltip for Menu Options

### ISSUE THREAD

**Issue by crydalch** [rjanja/desktop-capture#38]
I find I forget the hotkeys, since I generally just use the menu itself to stop a recording. And it got me thinking: it'd be hefpful if the hotkey would pop up as a tooltip after 1.5-2 seconds of hovering over a menu item (if it has a hotkey associated with it).

I don't know if that's even an option, but something that'd be nice in the future!

Thanks!

**Comment by rjanja** [comment]
Hi,

I agree, this would be a helpful addition. I will look into it. Thanks for the feedback!

**Comment by rjanja** [comment]
@crydalch I've posted an updated 1.03 with support for displaying hotkeys. Thanks for the great feedback and let me know if you have any questions or problems with this!

![screenshot-cinnamon-2015-09-17-171037](https://cloud.githubusercontent.com/assets/164802/9949210/5bb67c96-5d5f-11e5-98de-687c5c3d8610.png)

**Comment by crydalch** [comment]
Aha! That's wonderful, so helpful! Thanks for adding it!
