### ISSUE TITLE
Icon on system tray much larger compare to usual icons

### ISSUE THREAD

**Issue by RoldanLT** [rjanja/desktop-capture#39]
and I don't see any options to re-size it, to make it smaller and similar size by other icons.
![Icon on system tray much larger]
(http://i.imgur.com/zI01UsU.png)

**Comment by rjanja** [comment]
Hi,

What is the height of your panel? (In Cinnamon Settings.) I will check this out.

For now you might go into the Desktop Capture applet settings and turn on the option to use the "symbolic" icon, it will appear much more like the standard icons.

**Comment by RoldanLT** [comment]
My panel height is the default for 17.2.
 Ow, that symbolic settings is great. all fine now :).

**Comment by rjanja** [comment]
Great to hear it. I've added a new icon that will scale properly, however it won't appear until the next minor version. Between that and the symbolic workaround, I'm going to close this. But let me know if you have any questions. Thanks for the feedback!
