### ISSUE TITLE
unable to upload to imgur

### ISSUE THREAD

**Issue by conrado** [rjanja/desktop-capture#40]
Hi, having some issues uploading to imgur, currently digging into how cinnamon applets work.

here's an .xsession-errors excerpt

    JS ERROR: !!!   Exception was: Error: Unable to construct boxed type Buffer since it has no zero-args <constructor>, can only wrap an existing one
    JS ERROR: !!!     message = '"Unable to construct boxed type Buffer since it has no zero-args <constructor>, can only wrap an existing one"'
    JS ERROR: !!!     fileName = '"/home/conrado/.local/share/cinnamon/applets/capture@rjanja/applet.js"'
    JS ERROR: !!!     lineNumber = '2309'
    JS ERROR: !!!     stack = '"([object _private_unknown_GLocalFile],[object _private_Gio_Task])@/home/conrado/.local/share/cinnamon/applets/capture@rjanja/applet.js:2309

**Comment by rjanja** [comment]
Hi,

What version of Cinnamon are you running?

**Comment by conrado** [comment]
Cinnamon 2.2.16

**Comment by rjanja** [comment]
Hi,

I haven't been able to reproduce this on my end. Can you give me some more information about what distro you're running, its version, etc. The more the better. I can then attempt to virtualize another installation and see if I can find a problem here.

**Comment by conrado** [comment]
Hey,

I was using Linux Mint 17 Qiana, I upgraded to 17.2 Rafaela and uploading was successful.

Thanks!

**Comment by rjanja** [comment]
Hi, great to hear it. Thanks for updating this ticket - let me know if you run into any other problems!

And it may not be clear or obvious, but there should be an imgur.log in your screenshot directory that stores each imgur URL and delete link in the event you capture something by mistake and want to remove it from the internets.
