### ISSUE TITLE
Toogles alignment in the popup menu

### ISSUE THREAD

**Issue by zagortenay333** [rjanja/desktop-capture#42]
They look pretty weird the way they are aligned. They should be positioned on the far right.

**Comment by rjanja** [comment]
I didn't try this with other themes..oops. It just "worked" on the current theme, and I didn't see an immediate need to force alignment since that could make RTL display even wonkier.

I'll test out some additional themes today.

**Comment by zagortenay333** [comment]
On my Tertia theme:
![selection_003](https://cloud.githubusercontent.com/assets/11144630/9962648/1da2bdfc-5e27-11e5-9d85-c81b1876ca76.png)

**Comment by rjanja** [comment]
Fixed in latest 1.05

**Comment by zagortenay333** [comment]
:+1:
