### ISSUE TITLE
Stylesheet inline comments

### ISSUE THREAD

**Issue by zagortenay333** [rjanja/desktop-capture#43]
Could you please throw in some comments in there. It looks like some of those selectors seem to be unused. E.g., `.tmp`, `.option-label`, `.label-group`, etc..

**Comment by rjanja** [comment]
Haven't given this enough attention. EOD today :-)

**Comment by rjanja** [comment]
Fixed in latest 1.05. Unused styles have been removed and a couple of others have been renamed more appropriately. Let me know if you have any questions!

**Comment by zagortenay333** [comment]
Sweet! I added styles for my Tertia theme already. Will add for the other eventually as well.

**Comment by rjanja** [comment]
Nice, looking over the CSS changes in your theme I'm excited to see how you've styled it. I'll check it out :-). Thanks for including support for this applet!
