### ISSUE TITLE
Status text in popup menu 

### ISSUE THREAD

**Issue by zagortenay333** [rjanja/desktop-capture#44]
The status text in the popup menu uses a custom selector (`.menu-context`) which really isn't necessary, Best would be to borrow the corresponding style from the popup-menus.

This way it will blend in better

**Comment by rjanja** [comment]
I couldn't find a built-in selector to use which would serve as a detail or context or status label, shaded appropriately. I could remove this selector but then the hotkey will display in the same format as the rest of the menu item. Which style do you recommend?

**Comment by zagortenay333** [comment]
I actually think they have an element for that; you can see it in the network applet when it says _connecting_ or _cable unplugged_.
It uses the `.popup-inactive-menu-item` selector.

Also the battery applet uses for the _Fully charged_ text.

**Comment by rjanja** [comment]
That gives it a lot of boldness. Maybe it's just my theme though.

![screenshot-cinnamon-2015-09-18-084955](https://cloud.githubusercontent.com/assets/164802/9963891/5156d97a-5de2-11e5-8005-c0b95f1d26f8.png)

**Comment by zagortenay333** [comment]
I made that theme. Yeah it's the theme's fault.

**Comment by rjanja** [comment]
I can't find a better style to use so I'm going to continue with applet style. I'll revisit this sometime in the future and see if anything has changed.

**Comment by zagortenay333** [comment]
You mean you don't like how themes are styling it?
