### ISSUE TITLE
Hotkey helpers for alternate recorders are not displayed

### ISSUE THREAD

**Issue by crydalch** [rjanja/desktop-capture#45]
Hey @rjanja, I don't know how I totally missed this earlier, but it looks like the applet doesn't display the helpful shortcuts when using alternative recording backends like Byzanz or FFMPEG. Sorry I didn't catch this originally!

Thanks as usual for all the hard work, really appreciate it!

![screenshot-area-2015-09-22-213433](https://cloud.githubusercontent.com/assets/458856/10036226/619d931c-6172-11e5-99be-810e04d7a16b.png)

**Comment by rjanja** [comment]
Hi, I've been mulling this over but haven't decided how best to support hotkeys for custom commands just yet. One problem is that there is no limit on how many custom recorder commands can be present, so "Record Window" in Byzanz could correspond to a different recording option in another recorder. 

This is something I want to do, but I'm pretty sure will require rewriting the Settings again, this time using the settings API but ditching the clunky, unorganized settings window in favor of a fully customizable display of screenshot and recorder apps. But that's a much larger effort, so maybe there's a middle ground to be found.

**Comment by crydalch** [comment]
Ah, yeah I can see that being trickier. 

What about the generic Start/Stop Recorder Hotkeys? Could those be displayed on the appropriate line?

**Comment by rjanja** [comment]
While I'd like to do this, keybindings can't be made conditional within the current Cinnamon Xlets Settings API, which means there'd either be a lot of extra keybinding options that aren't always used (and lead to confusion) or we'd need to move back to an external settings application. I'm not too excited about either of these options, so for now I'm just going to close this.
