### ISSUE TITLE
Imgur upload not work

### ISSUE THREAD

**Issue by pepijol82** [rjanja/desktop-capture#48]
First of all I'm want thank you for your great applet.
It amazing and works well better than native ImgurUploader with Wine.

All works good with my Linux Mint 17.3 Cinnamon 2.8.8.

But not work Imgur Upload function.

Looking Glass tool show me error:

> Error during upload: response code 404: Not Found - {"data":{"error":"The version of the Imgur API you are using is no longer available","request":"\/2\/upload.json","method":"POST"},"success":false,"status":404}

Please help me to fix this issue.

**Comment by rjanja** [comment]
Hi, thanks for the report.

Imgur notified me some time ago that they were dropping support for the version of their API I used in this applet. After looking through their docs and reaching out to them a handful of times I came to the conclusion that there was not a simple replacement to keep things working the same way.

One alternative would be to ask the user to create an Imgur API account and then plug their credentials into this applet. The applet could then manage requesting new tokens as needed as access tokens expire. But there still doesn't appear to be a good way to intuitively guide the user through this process, so I'm reluctant to add this. I will consider it again, though.

Any other uploading tools you use that might be better fits with this applet?

Thanks for the kind feedback!

**Comment by rjanja** [comment]
I think I have found a good way to do this and support imgur via oauth 2.0 from this applet. I'll do some experimenting and aim for a release towards the end of January.

**Comment by rjanja** [comment]
The next major update will support anonymously uploading images to imgur, as well as authorizing the applet to upload images into an album in your account using an included helper application. 

![screenshot-area-2017-01-22-212824](https://cloud.githubusercontent.com/assets/164802/22192561/e4aecb3e-e0e9-11e6-8396-52ff3a4be990.png)

![screenshot-window-2017-01-21-194953](https://cloud.githubusercontent.com/assets/164802/22192515/945b16a6-e0e9-11e6-8b7b-7846bd027309.png)

![screenshot-window-2017-01-21-194249](https://cloud.githubusercontent.com/assets/164802/22192520/97ab6658-e0e9-11e6-90bd-a56695fde519.png)

**Comment by pepijol82** [comment]
Thank you very much! It is the best gift to the Chinese New Year for me! :-)
You are my hero! :+1:

**Comment by rjanja** [comment]
Thanks for the kind words @pepijol82 ! 
Hope you had a wonderful Chinese New Year! :-)
The new version is not published on Spices site yet, so if you have trouble getting it from Github let me know. Cheers!
