### ISSUE TITLE
Totally kills cinnamon-3.2.x

### ISSUE THREAD

**Issue by leigh123linux** [rjanja/desktop-capture#49]
```
(cinnamon:13499): Cjs-WARNING **: JS ERROR: Exception in callback for signal: activate: TypeError: this._boxPointer is undefined
MyAppletPopupMenu.prototype.close@/home/leigh/.local/share/cinnamon/applets/capture@rjanja/applet.js:369
PopupMenuBase.prototype._connectItemSignals/menuItem._activateId<@/usr/share/cinnamon/js/ui/popupMenu.js:1861
_emit@resource:///org/gnome/gjs/modules/signals.js:140
PopupBaseMenuItem.prototype.activate@/usr/share/cinnamon/js/ui/popupMenu.js:177
PopupBaseMenuItem.prototype._onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:150
```

**Comment by erdoking** [comment]
same here, using cinnamon 3.2.2 on OpenSuse Leap 42.2

I found out, that the "camera-save-dir" is wrong in ~/.cinnamon/configs/capture@rjanja/capture@rjanja.json!!

after changing  "value": "file:///tmp" to "value": "/tmp" and comment out line 369 in .local/share/cinnamon/applets/capture@rjanja/applet.js it start working again...

> //      this._boxPointer.hide(this._animateClose);

But the select-menu won't close. I have to restart cinnamon after taking screnshot!

**Comment by rjanja** [comment]
Thanks for the reports. I'll be looking into this tomorrow and should be able to get a patch out soon.

**Comment by rjanja** [comment]
Hi, I've pushed an update to this applet as 1.06 that should clear up the compatibility problems with Cinnamon 3.2. Could you please try it again and let me know if it resolves this problem? Thanks!

**Comment by fggomes** [comment]
I've updated the code to 1.06 and the problem was resolved. Thank you, I love this applet.

**Comment by rjanja** [comment]
Great, thanks for getting back to me so fast! Glad it's working for you again!
