### ISSUE TITLE
notification-with-image css selector not used

### ISSUE THREAD

**Issue by zagortenay333** [rjanja/desktop-capture#51]
Isn't this code supposed to add that selector:
https://github.com/rjanja/desktop-capture/blob/4cde330caa5bf2b15adc8c408bab9375ea8cc383/capture%40rjanja/applet.js#L163-L165

**Comment by rjanja** [comment]
Yes. What theme are you testing?

**Comment by zagortenay333** [comment]
No need to test it with a theme, just use the looking glass. Also most themes don't make a distinction to be able to see it.
https://github.com/zagortenay333/ciliora-secunda-cinnamon

**Comment by rjanja** [comment]
Thanks @zagortenay333, I've corrected the code that *should* have been adding the CSS class.

Please note that this fix won't appear until release of 1.09, which has to wait until the Cinnamon Spices site is back up and available to applet authors. For now I can't upload any new versions.

Here is what this style looks like on stock Cinnamon theme. The 159px is the default from the `cinnamon.css`.

```
#notification.notification-with-image {
   min-height: 159px;
   background-color: green;
}
```
![screenshot-area-2016-12-31-170924](https://cloud.githubusercontent.com/assets/164802/21579861/3fee4b0c-cf7c-11e6-9057-e735290d91f9.png)

**Comment by zagortenay333** [comment]
Nice, but how come you can't upload to spices? Didn't you update it just 3 days ago?

**Comment by rjanja** [comment]
Yes. The Cinnamon Spices are themselves being migrated to Github for the purpose of undergoing code reviews before publishing. No applets can currently be updated, unfortunately. If you'd like I can drop a zip file somewhere for you.

**Comment by zagortenay333** [comment]
Oh.

Nah, I already installed. It work as it should now.
