### ISSUE TITLE
Show capture timer checkbox broken

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#52]
The "Show capture timer" checkbox seems broken.

EDIT: It means, that the timer is shown, no matter if the checkbox/switcher is checked or not.

**Comment by NikoKrause** [comment]
The ReadMe file wasn't updated 4 years. Maybe you can add "Compatible Cinnamon versions"?

Do you wanna add multiversion to your applet?
Since 3.0/3.2? it's possible to add Tabs/Pages to the settings. It would make the settings look cleaner and easier to find stuff. But it would break the applet for minor Cinnamon versions, that's why I suppose multiversion.
It you up for the idea, I can help you with that.

**Comment by rjanja** [comment]
I'm not sure how many people are using this applet on older versions if Cinnamon. I'd prefer to support all versions but only if it didn't require much more of an investment of time. 

If you'd like to show me how multi version works that'd be great. One of the recent breaking changes I added was a setting of type `label` to `settings-schema.json`. I'd found out that undefined settings types crashed settings API in previous versions and had just left it commented until recently. It would be nice to target specific versions.

Thanks for the feedback!

**Comment by NikoKrause** [comment]
If you add multiversion support, you don't have to support all versions.
You can if you want to. But you can also say you just support the new Cinnamo version and leave the old ones as they are. The benefit is that you can go and implement new features without having to break the applet for older versions with new updates.

Here is a quick tutorial: http://developer.linuxmint.com/reference/2.6/cinnamon-tutorials/xlet-versioning.html

If you need more help with that I can create a pull request.

**Comment by NikoKrause** [comment]
With tabs I mean this: `Leiste` and `Menü`. E.g. open settings for the menu-applet on Cinnamon 3.2
![grafik](https://cloud.githubusercontent.com/assets/8415124/21589899/f3c2fe18-d0f6-11e6-90ab-b9ec2db364f2.png)

**Comment by NikoKrause** [comment]
@rjanja 
I'm working on a german translation of your applet.

Can you explain me the following strings:
1. Capture window as area
2. Include applied styles in UI capture

Maybe with examples.

I'll create a PR, when I'm finnished. Probably in 2-3 days.
