### ISSUE TITLE
Feature request: Make "Camera" and "Recorder" buttons useful

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#53]
If you click on the applet, the popupmenu opens.
In this PopupMenu there are two buttons "Camera" and "Recorder".
These buttons do nothing, when pressed.

I would suggest to open the Screenshot-Program and the Recorder-Program, which are set in the settings, with those buttons.

**Comment by rjanja** [comment]
The options listed for camera and recorder currently come from `support.json`, so we could do this by way of defining in that file a "default" command to run for any GUI-capable apps, and leave it unset and unused for non-GUI apps like the built-in screenshot and recorder which do not have interactive utilities.

**Comment by NikoKrause** [comment]
Sounds good.

**Comment by rjanja** [comment]
Support for this has been added in 9e3b32355ed2ff56d5b2ed8ea9ecf4091ba5c1c4 (1.09)
