### ISSUE TITLE
Timer for Cinnamon UI too soon

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#59]
When you use timer in "Area" capture, the timer starts after pressing Enter.
When you use timer in "Cinnamon UI" capture, the timer starts before showing the green info box. It would make more sense, if it would start after mouse click, so right before taking the actual capture.

**Comment by rjanja** [comment]
This is a bit of a personal preference that I could make into a setting. When I use the UI capture, I like to have some time to change focus and open up any part of the UI that I am about to capture, so I use the timer to allow for that before it begins drawing selection masks and elements.

_Timer begins immediately in UI capture_
"Allows for changing focus and opening menus before selection masks are drawn"

What do you think? Would this align more with your expectations? I'm also interested in what the timer post-selection would allow the user to do for UI captures, it doesn't seem as useful as it is in Window and Area selection modes.

**Comment by NikoKrause** [comment]
Ah okay. I didn't realize, that you can click UI during Timer-Countdown (I always waited till the green box appeared, to continue with the capture.)
But that's what SHIFT is for, not? You have all the time you want to open menus, when pressing SHIFT.

I'm not sure anymore, about how doing it the right way or even if a timer for UI is needed.

For me a timer is: 3...2...1...snap
But in this case, it's 3....(still having some time to open stuff)......2...1.....green box appears.....now having inifinite time to change focus or opening new stuff with SHIFT.

But it's pointless in having the green box, then setting focus and opening menus with SHIFT and then having a timer 3....(There is nothing you can change now, just waiting the picture to kick in)......2...1...snap

You are right: a timer post-selection for UI captures doesn't seem as useful as it is in Window and Area selection modes.

I got it now, why you made it this way. I think the thing that confused me is, that the Green Box appears after the timer.

Leaving it as it is, is probably the best choice.

Maybe adding an option: "Don't use Timer in UI capture"
How do you think about it?

**Comment by NikoKrause** [comment]
Nevermind. I thought about it a little bit. This would be an overkill of options. It's fine as it is. I'm closing this issue.
