### ISSUE TITLE
Multiversion Support and Settings Schema suggestion

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#60]
Hey,

I added multiversion support and changed the settings-schema in my branch https://github.com/NikoKrause/desktop-capture/tree/multversion-support

I did multiversion for Cinnamon >= 2.6.
I don't know if the applet works for Versions < 2.6
If yes, this can be added as well.

I didn't created a PR. First I wanted to give you a suggestion of how it can look like, so you can check it out.

Here are Screenshots of my suggestion for Settings in 3.2:
![screenshot-window-2017-01-06-194206](https://cloud.githubusercontent.com/assets/8415124/21729601/f9937d24-d44b-11e6-8292-653995c4fc43.png)
![screenshot-window-2017-01-06-194214](https://cloud.githubusercontent.com/assets/8415124/21729598/f98ec7c0-d44b-11e6-8995-1d38ebdf6c77.png)
![screenshot-window-2017-01-06-194238](https://cloud.githubusercontent.com/assets/8415124/21729599/f98fb9fa-d44b-11e6-879a-fcefa982223a.png)
![screenshot-window-2017-01-06-194247](https://cloud.githubusercontent.com/assets/8415124/21729600/f98ffbe0-d44b-11e6-9875-384877085f29.png)

**Comment by rjanja** [comment]
Thanks for the effort you put into this @NikoKrause. I've used that as a template and have added multiversion support and settings tabs. Cheers!
