### ISSUE TITLE
Black box around the mouse cursor

### ISSUE THREAD

**Issue by crydalch** [rjanja/desktop-capture#62]
I've noticed the mouse cursor has a black box around it; is this an issue with Cinnamon, or with the desktop-capture applet? This is Mint 18.1, Cinnamon 3.2.7.

![screenshot-area-2017-01-09-210930](https://cloud.githubusercontent.com/assets/458856/21791382/58cc44f4-d6b0-11e6-8a46-7c1c4ac4dbfe.png)

Thanks

**Comment by crydalch** [comment]
FWIW, with maim I don't see the blackbox:

![foobar2](https://cloud.githubusercontent.com/assets/458856/21791521/591c8634-d6b1-11e6-9d08-5084680ee027.png)

**Comment by rjanja** [comment]
Hi, thank you for the feedback. What is maim?
Does the cursor show a black box for you even when you don't use this applet to take a screenshot?

**Comment by crydalch** [comment]
Hey! This is maim:[https://github.com/naelstrof/maim]( https://github.com/naelstrof/maim)

I don't see the box if I use gnome-screenshot -p from the commandline. How do I take a native cinnamon screenshot?

**Comment by rjanja** [comment]
maim and gnome-screenshot both use X to take the screenshots. desktop-capture applet uses cinnamon for its screenshots.

I have been able to reproduce this when capturing the mouse cursor. This is a Cinnamon problem, for sure.

**Comment by NikoKrause** [comment]
I can reproduce it.
![screenshot-cinnamon-2017-01-25-102748](https://cloud.githubusercontent.com/assets/8415124/22285069/6c2fd236-e2ea-11e6-9fc9-a439798d4adb.png)

Also I tried to take a screenshot of the whole desktop. The screen started flickering like crazy and I get a bunch of the warning below:
```
(cinnamon:5132): Cjs-WARNING **: JS ERROR: GdkPixbuf.PixbufError: Unrecognized image file format
MyApplet.prototype.maybeSendNotification@/home/krause/.local/share/cinnamon/applets/capture@rjanja/applet.js:1319
MyApplet.prototype.cinnamon_camera_complete@/home/krause/.local/share/cinnamon/applets/capture@rjanja/applet.js:1284
ScreenshotHelper.prototype.runCallback@/home/krause/.local/share/cinnamon/applets/capture@rjanja/screenshot.js:856
ScreenshotHelper.prototype.screenshotScreen/<@/home/krause/.local/share/cinnamon/applets/capture@rjanja/screenshot.js:640
```

**Comment by crydalch** [comment]
Thanks guys, logged a ticket against Cinnamon. @rjanja, do you want to close this, or leave it open until it gets fixed upstream? I'm fine either way.

**Comment by rjanja** [comment]
I think we can close this. While I'd like to help hunt this down in Cinnamon, I just don't have the time these days. Thanks @crydalch

**Comment by NikoKrause** [comment]
https://github.com/linuxmint/Cinnamon/commit/b9dc41846ddb5aedabf962c20acfc71aec46d5d5
