### ISSUE TITLE
Issues with recorder / ffmpeg

### ISSUE THREAD

**Issue by scasic** [rjanja/desktop-capture#68]
Recorder does nothing on Cinnamon 3.2.7 / Linux Mint 18.1 Serena with ffmpeg specified as capture tool. There are no resulting files in configured folder. 

Also on previous versions I was able to select capture area using mouse click and drag&down move, now it doesn't work. Only drag&up move makes an area selected.

**Comment by rjanja** [comment]
Hi, thanks for the feedback. Can you please verify first that you have `ffmpeg` installed, and then let me know what version is installed? Due to the way Cinnamon Settings is designed, there is no easy way for my applet settings to detect which programs are installed, so they are all listed.

When you attempt to make a recording using ffmpeg, the actual command being run is logged to `~/.cinnamon/glass.log` (if Cinnamon logging is enabled in Cinnamon Settings -> General). What happens when you run this command from a terminal yourself?

Finally, the capture instructions screen was changed to be consistent between UI capture and Area capture where a single mouse click is needed to dismiss the instructions. But dragging in either direction should work to select an area, are you saying it does not?

**Comment by scasic** [comment]
ffmpeg is installed, please see output of executed command which was taken from glass.log below: 

> ~ $ ffmpeg -f alsa -ac 2 -i pulse -f x11grab -s 560x366 -r 30 -qscale 1 -i :0.0+649,382 /home/user1/Videos/screencast-2017-03-12-234817.mkv
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Guessed Channel Layout for  Input Stream #0.0 : stereo
Input #0, alsa, from 'pulse':
  Duration: N/A, start: 1489351770.517955, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
Option qscale (use fixed quality scale (VBR)) cannot be applied to input url :0.0+649,382 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file :0.0+649,382.
Error opening input files: Invalid argument

As for dragging please ignore my statement, i can't reproduce it anymore.

**Comment by rjanja** [comment]
Ok, could you please try this workaround:

1. Open up `support.json` in applet directory e.g. `~/.local/share/cinnamon/applets/capture@rjanja/3.2/support.json`
2. Find the `ffmpeg` recorder options towards the bottom
3. Remove `-qscale 1` from the three included commands
4. Reload Cinnamon (Alt+F2, "r", <ENTER>)
5. Try recorder again

If that works I can push an update. Thanks!

**Comment by rjanja** [comment]
Hi, did that fix the problem for you?
