### ISSUE TITLE
error: redeclaration of let psCursorOn on Cinnamon 3.4.2

### ISSUE THREAD

**Issue by guzzard** [rjanja/desktop-capture#70]
when trying to load current git master version:

error t=2017-06-23T20:45:01.613Z redeclaration of let psCursorOn
trace t=2017-06-23T20:45:01.613Z 
<----------------
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155:13
Extension@/usr/share/cinnamon/js/ui/extension.js:116:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449:25
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:236:13
---------------->
error t=2017-06-23T20:45:01.613Z [Applet "capture@rjanja"]: Error importing applet.js from capture@rjanja
error t=2017-06-23T20:45:01.613Z Could not load applet capture@rjanja

**Comment by rjanja** [comment]
Hi @guzzard, thanks for your bug report. I've pushed an update which should correct it. If you have time to give it a try I'd appreciate your feedback.

Thanks again!

**Comment by guzzard** [comment]
Hi @rjanja, I can confirm that it works great again, thanks! :+1:

**Comment by rjanja** [comment]
Wonderful! Thanks for following up, @guzzard! 😎

**Comment by guzzard** [comment]
Anytime! Thanks for your hard work on this great applet @rjanja ! :+1: :smiley:

**Comment by NikoKrause** [comment]
Just upgraded to Cinnamon 3.4 and got the same error. Came here to fix it and now see it's already fixed.
