### ISSUE TITLE
non-fatal error reported by cinnamon on dual screen setup

### ISSUE THREAD

**Issue by TopView** [rjanja/desktop-capture#71]
In my Cinnamon Log when restarting cinnamon I see:

  "error t=2017-06-29T15:42:24Z Could not find setting key 'kb-cs-monitor-1' for applet/desklet uuid capture@rjanja" .  

My system is Debian stretch (just upgraded from Jessie) on a HP laptop with 1 extra slightly larger screen plugged into the video port.

Only get this error if booting up w/ both screens.  If just laptop screen then no error.

Also I have one other anomaly here that might be related to this.  When I boot up the login appears on the non-primary (or second screen).  I'm still scratching my head about this one.  So this issue might not be yours.  I really don't know.

Also not sure if this was in my older Jessie setup or not, as I am still learning to check the logs for errors. 

Except for this error message, desktop-capture seems to work find.  I tested each of the captures on both screens.

ENTIRE LOG IS

nfo t=2017-06-29T15:42:21Z Cinnamon.AppSystem.get_default() started in 183 ms
info t=2017-06-29T15:42:21Z loading user theme: /usr/share/themes/BlueMenta/cinnamon/cinnamon.css
info t=2017-06-29T15:42:21Z added icon directory: /usr/share/themes/BlueMenta/cinnamon
info t=2017-06-29T15:42:21Z PlacesManager: Updating devices
info t=2017-06-29T15:42:21Z loaded at Thu Jun 29 2017 15:42:21 GMT-0700 (PDT)
info t=2017-06-29T15:42:22Z Role locked: panellauncher
info t=2017-06-29T15:42:22Z Loaded applet panel-launchers@cinnamon.org in 331 ms
info t=2017-06-29T15:42:22Z Loaded applet window-list@cinnamon.org in 53 ms
info t=2017-06-29T15:42:24Z Loaded applet menu@cinnamon.org in 2154 ms
info t=2017-06-29T15:42:24Z Loaded applet systray@cinnamon.org in 9 ms
info t=2017-06-29T15:42:24Z Loaded applet separator@cinnamon.org in 6 ms
info t=2017-06-29T15:42:24Z Loaded applet show-desktop@cinnamon.org in 12 ms
info t=2017-06-29T15:42:24Z Loaded applet recent@cinnamon.org in 24 ms
info t=2017-06-29T15:42:24Z Loaded applet windows-quick-list@cinnamon.org in 8 ms
info t=2017-06-29T15:42:24Z Loaded applet spacer@cinnamon.org in 11 ms
info t=2017-06-29T15:42:24Z Role locked: notifications
info t=2017-06-29T15:42:24Z Loaded applet notifications@cinnamon.org in 16 ms
info t=2017-06-29T15:42:24Z Loaded applet sound@cinnamon.org in 61 ms
info t=2017-06-29T15:42:24Z Loaded applet network@cinnamon.org in 78 ms
info t=2017-06-29T15:42:24Z Loaded applet calendar@cinnamon.org in 24 ms
info t=2017-06-29T15:42:24Z Loaded applet power@cinnamon.org in 21 ms
info t=2017-06-29T15:42:24Z undefined: Spawned process with pid=2698
info t=2017-06-29T15:42:24Z capture@rjanja: Using AppletSettings
info t=2017-06-29T15:42:24Z capture@rjanja: [disabled] imgur
error t=2017-06-29T15:42:24Z Could not find setting key 'kb-cs-monitor-1' for applet/desklet uuid capture@rjanja
info t=2017-06-29T15:42:24Z Loaded applet capture@rjanja in 260 ms
info t=2017-06-29T15:42:24Z AppletManager.init() started in 3102 ms
info t=2017-06-29T15:42:24Z Loaded desklet launcher@cinnamon.org in 9 ms
info t=2017-06-29T15:42:25Z Loaded desklet devTools@scollins in 44 ms
info t=2017-06-29T15:42:25Z Loaded desklet clock@cinnamon.org in 12 ms
info t=2017-06-29T15:42:25Z Loaded desklet simple-system-monitor@ariel in 28 ms
info t=2017-06-29T15:42:25Z Loaded desklet photoframe@cinnamon.org in 39 ms
info t=2017-06-29T15:42:25Z Cinnamon took 3592 ms to start
info t=2017-06-29T15:42:26Z capture@rjanja: Support for open folder/file enabled
info t=2017-06-29T15:42:27Z Hiding systray: network
info t=2017-06-29T15:43:29Z Spawning xdg-open file:///home/howard/Media/Pictures/ScreenShots
info t=2017-06-29T15:43:34Z Spawning xdg-open file:///home/howard/Media/Pictures/ScreenShots
info t=2017-06-29T15:51:31Z Initializing screenshot tool
info t=2017-06-29T15:51:53Z Initializing screenshot tool
info t=2017-06-29T15:51:57Z Selection area is 922,301 - 202 x 147
info t=2017-06-29T15:52:13Z Initializing screenshot tool
info t=2017-06-29T15:52:30Z Initializing screenshot tool
info t=2017-06-29T15:52:40Z Initializing screenshot tool
info t=2017-06-29T15:52:47Z Initializing screenshot tool
info t=2017-06-29T15:52:58Z Initializing screenshot tool
info t=2017-06-29T15:53:21Z Initializing screenshot tool
info t=2017-06-29T15:53:39Z Capturing screencast to /home/howard/Media/Pictures/ScreenShots/screencast-2017-06-29-155339.webm
info t=2017-06-29T15:53:39Z Pipeline is 
info t=2017-06-29T15:54:47Z Initializing screenshot tool
info t=2017-06-29T15:54:54Z Selection area is 861,403 - 464 x 264
info t=2017-06-29T15:55:08Z undefined: Spawned process with pid=2984
info t=2017-06-29T15:55:39Z Capturing screencast to /home/howard/Media/Pictures/ScreenShots/screencast-2017-06-29-155539.webm
info t=2017-06-29T15:55:39Z Pipeline is

**Comment by rjanja** [comment]
Hi @TopView, thanks for the bug report. It looks like the code is trying to work with applet settings that just don't exist (hotkeys for monitors after the primary, so 2+). The idea originally was that per-monitor hotkeys could be defined, and then I think I abandoned that approach as it was going to clutter up the settings where there's no way to conditionally show things. 

I'm not sure which versions of Cinnamon treat this as a serious applet error, but I'll try to find some time soon to get it fixed.

The solution for now is probably to limit the monitor hotkeys support to three monitors, and to add monitors 2 and 3 to the settings schema for capture hotkeys.

For the time being, this problem can be avoided by editing this applet's `settings-schema.json` and duplicating this block of code for each additional monitor that is connected:
```
   "kb-cs-monitor-0" : {
      "indent": true,
      "type" : "keybinding",
      "description" : "Keybinding to capture monitor 1: ",
      "default" : "<Control>F9"
   },
```
Use "kb-cs-monitor-0", "kb-cs-monitor-1", "kb-cs-monitor-2" etc for each additional monitor you wish to capture with hotkeys (or to avoid this error in cinnamon.log). Also updating the descriptions is probably a good idea if you take this approach.

E.g.
```
   "kb-cs-monitor-0" : {
      "indent": true,
      "type" : "keybinding",
      "description" : "Keybinding to capture monitor 1: ",
      "default" : "<Control>F9"
   },
   "kb-cs-monitor-1" : {
      "indent": true,
      "type" : "keybinding",
      "description" : "Keybinding to capture monitor 2: ",
   },
   "kb-cs-monitor-2" : {
      "indent": true,
      "type" : "keybinding",
      "description" : "Keybinding to capture monitor 3: ",
   },
```

Cheers,
Rob

**Comment by TopView** [comment]
Rob,

Ok thanks, but to edit the settings-schema.json, *which one do I edit?* 
|I find these two versions on my system:|

|~/.local/share/cinnamon/applets/capture@rjanja/2.6/settings-schema.json|
|    ~/.local/share/cinnamon/applets/capture@rjanja/3.2/settings-schema.json
|
|When looking at the About dialog I see:

||    Desktop Capture v1.12
     capture@rjanja
     Screenshot and screencasting tools
|||

_____________
BTW, I think it would be helpful if you added a button to the About 
dialog which would allow the image of it to be captured, so I could just 
snap it and attach it to my email, so you can see the version I'm 
using.  I was able to do this w/ a timer:

**Comment by TopView** [comment]
ah, never mind, I see you have one for each different version of 
Cinnamon that I have used.  I'll edit the 3.2 version.  Thanks!

**Comment by TopView** [comment]
Yes, the edit you suggested made the error go away.  Very good!  Thanks 
again.

**Comment by rjanja** [comment]
Great, thanks for confirming the work-around! I'll try to push a fix this weekend or next.

Thanks for all the feedback!

**Comment by rjanja** [comment]
I've pushed a fix as 1.13 - if you could find some time this week or next to give it a try I'd appreciate hearing whether it addresses the problem. Thanks much!

**Comment by TopView** [comment]
Rob,

I wasn't sure how to upgrade as I haven't done that much.  I tried the 
update button, but nothing.  So finally ended up uninstalling, and then 
thought I might re-load, but then I couldn't find this in the list.  
:-/  I finally went to your instructions at git to figure out how to 
download and install it. Ok, that step done.


Now, unfortunately, there are still errors.

info:  7/05 13:37:34  Cinnamon.AppSystem.get_default() started in 376 ms
info:  7/05 13:37:34  loading user theme: 
/usr/share/themes/BlueMenta/cinnamon/cinnamon.css
info:  7/05 13:37:34  added icon directory: 
/usr/share/themes/BlueMenta/cinnamon
info:  7/05 13:37:34  PlacesManager: Updating devices
info:  7/05 13:37:34  loaded at Wed Jul 05 2017 13:37:34 GMT-0700 (PDT)
info:  7/05 13:37:37  Loaded applet menu@cinnamon.org in 2520 ms
info:  7/05 13:37:37  Role locked: panellauncher
info:  7/05 13:37:37  Loaded applet panel-launchers@cinnamon.org in 413 ms
info:  7/05 13:37:37  Loaded applet window-list@cinnamon.org in 47 ms
info:  7/05 13:37:38  Loaded applet recent@cinnamon.org in 58 ms
info:  7/05 13:37:38  Loaded applet show-desktop@cinnamon.org in 16 ms
info:  7/05 13:37:38  Loaded applet systray@cinnamon.org in 16 ms
info:  7/05 13:37:38  Loaded applet windows-quick-list@cinnamon.org in 24 ms
info:  7/05 13:37:38  Loaded applet expo@cinnamon.org in 12 ms
info:  7/05 13:37:38  Role locked: notifications
info:  7/05 13:37:38  Loaded applet notifications@cinnamon.org in 21 ms
info:  7/05 13:37:38  Loaded applet weather@mockturtl in 49 ms
info:  7/05 13:37:38  Loaded applet sound@cinnamon.org in 67 ms
info:  7/05 13:37:38  Loaded applet network@cinnamon.org in 85 ms
info:  7/05 13:37:38  Loaded applet calendar@cinnamon.org in 21 ms
info:  7/05 13:37:38  Loaded applet power@cinnamon.org in 21 ms
info:  7/05 13:37:38  Loaded applet ScreenShot+RecordDesktop@tech71 in 19 ms
info:  7/05 13:37:38  Loaded applet ScreenShot@tech71 in 14 ms
info:  7/05 13:37:38  AppletManager.init() started in 3465 ms
info:  7/05 13:37:38  Loaded desklet launcher@cinnamon.org in 8 ms
info:  7/05 13:37:38  Loaded desklet clock@cinnamon.org in 11 ms
info:  7/05 13:37:38  Loaded desklet devTools@scollins in 71 ms
info:  7/05 13:37:38  Cinnamon took 4240 ms to start
info:  7/05 13:37:41  Hiding systray: network
info:  7/05 13:38:43  Hiding systray: network
info:  7/05 13:38:43  undefined: Spawned process with pid=14812
info:  7/05 13:38:43  Installing settings for capture@rjanja
error:  7/05 13:38:43  Settings key kb-cs-monitor-1 is missing property 
default
info:  7/05 13:38:43  capture@rjanja: Using AppletSettings
info:  7/05 13:38:43  Save folder does not exist: 
/home/howard/Pictures/screenshots, aborting
error:  7/05 13:38:43  this.monitor is undefined
trace:  7/05 13:38:43
<----------------
XletSettingsBase.prototype._saveToFile@/usr/share/cinnamon/js/ui/settings.js:723
XletSettingsBase.prototype._setValue@/usr/share/cinnamon/js/ui/settings.js:454
XletSettingsBase.prototype.setValue@/usr/share/cinnamon/js/ui/settings.js:486
MyApplet.prototype.parseSaveFolder@/home/howard/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js:663
MyApplet.prototype._onSettingsChanged@/home/howard/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js:577
MyApplet.prototype._initSettings@/home/howard/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js:459
MyApplet.prototype._init@/home/howard/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js:773
MyApplet@/home/howard/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js:418
main@/home/howard/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js:2277
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:404
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:294
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
info:  7/05 13:38:43  Loaded applet capture@rjanja in 90 ms
info:  7/05 13:38:43  Hiding systray: network
info:  7/05 13:38:43  capture@rjanja: Support for open folder/file enabled
info:  7/05 13:40:12  Hiding systray: network
info:  7/05 13:40:12  Hiding systray: network
info:  7/05 13:40:17  Hiding systray: network
info:  7/05 13:40:17  undefined: Spawned process with pid=14956
info:  7/05 13:40:17  Upgrading settings for capture@rjanja
info:  7/05 13:40:17  Settings successfully upgraded for capture@rjanja
info:  7/05 13:40:17  capture@rjanja: Using AppletSettings
info:  7/05 13:40:17  Save folder does not exist: 
/home/howard/Videos/screencasts, aborting
info:  7/05 13:40:17  capture@rjanja: [disabled] imgur
info:  7/05 13:40:17  Loaded applet capture@rjanja in 143 ms
info:  7/05 13:40:17  Hiding systray: network
info:  7/05 13:40:17  capture@rjanja: Support for open folder/file enabled
info:  7/05 13:40:59  loading default theme
info:  7/05 13:40:59  Hiding systray: network

Let me know when to try again.  Thanks

-- Howard

**Comment by rjanja** [comment]
Hi @TopView, sorry about that! I've pushed up another fix if you wouldn't mind trying again.
