### ISSUE TITLE
add option to hide the info for area and Cinnamon UI

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#72]
When you use `Area` and `Cinnamon UI` you get an info about how to use this.
It's annoying to always use an extra click to make the info disappear. Can you add an option to hide this info?

**Comment by rjanja** [comment]
Thanks for the feedback. Yes, I can look into making this less annoying. The behavior of the two modes used to be different, but I felt the instructions could be too easily dismissed by accident so I added the requirement of a click.

I'll take a look at how it might work without dismissing instructions with a click in either mode.

**Comment by rjanja** [comment]
Updated behavior:

* Area selection: instructions are dismissed as soon as mouse is clicked, and mouse clicking begins area selection.
* UI selection: instructions are dismissed as soon as the mouse pointer has traveled 200 pixels in any diretion

**Comment by NikoKrause** [comment]
Cool. I'll try tomorrow.

**Comment by NikoKrause** [comment]
Thank you. This feels much better now.
