### ISSUE TITLE
some JS warning

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#74]
I see some JS warnings in `xsession-errors`:

```
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js 433]: reference to undefined property this._uuid
```
and
```
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 398]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 399]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 400]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 401]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 1109]: reference to undefined property event.get_source(...).style_class
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js 1306]: Too many arguments to method St.TextureCache.load_uri_sync: expected 4, got 5

```

**Comment by rjanja** [comment]
Which version of Cinnamon are you running? I'm not seeing the latter group of warnings in 3.2, so I suspect some Clutter method signatures have changed and we'll need a new multi-version target.

**Comment by NikoKrause** [comment]
I use Cinnamon 3.4. But I get those only when actually using the applet. 

I try to figure out the steps to reproduce them. I'll let you know, when I have more info.

**Comment by NikoKrause** [comment]
So looking at xsession-errors here:

* [This St.TextureCache.get_default().load_uri_sync method](https://github.com/rjanja/desktop-capture/blob/b5a74283460bc92baee8a82cb18b5257c2d4cb46/capture%40rjanja/3.2/applet.js#L1307-L1311) got 5 arguments but it expects 4 arguments. The last argument `scaleFactor` seems to be too much, according to [the comments of st_texture_cache_load_uri_sync](https://github.com/linuxmint/Cinnamon/blob/b8ea0e1c102969310e5507e97d408f2b58b16d0a/src/st/st-texture-cache.c#L1587-L1610)

* [This add_actor methods](https://github.com/rjanja/desktop-capture/blob/master/capture%40rjanja/3.2/screenshot.js#L403-L406) has 2 arguments but expects 1. You should remove the second argument.

I get those warnings, when taking screenshots with "Area".
I don't think you need to add a new multi-version target for that.
