### ISSUE TITLE
Imgur integration wizard doesn't work in Mint 18.2

### ISSUE THREAD

**Issue by Roman-Skripka** [rjanja/desktop-capture#75]
Updated to Mint 18.2 from 18.1 and applet stopped working, after reset can't link imgur account, nothing happens after clicking "Wizard: Connect to your account..." button. Other functionality and anonymous uploading seems to work well.
Cinnamon version is 3.4.6
Applet version is 1.14
![screenshot-area-2017-09-04-120615](https://user-images.githubusercontent.com/7115589/30019527-8ee8893e-9169-11e7-8470-c5ba467f4905.png)

**Comment by rjanja** [comment]
Hi, thanks for the feedback. It sounds like something has changed in Cinnamon 3.4, maybe a dependency was bumped.

I'm out of town for a week so I won't be able to review this until around 9/12, but I appreciate you filing a ticket.

**Comment by NikoKrause** [comment]
Created a PR to fix the imgur wizard

**Comment by Roman-Skripka** [comment]
@NikoKrause Thank you, worked like a charm
