### ISSUE TITLE
Feature Request: Add delay to popup menu

### ISSUE THREAD

**Issue by NikoKrause** [rjanja/desktop-capture#78]
Right now capture delay is in the settings.
It would be convenient to be able to change the delay in the applets popup itself.

A slider could be used.

**Comment by rjanja** [comment]
Hi, thanks for the feedback!

There used to be a select menu but it was a bit awkward to use and only had a few durations to choose between. A slider might work fine for this.

What range of delays would be useful for you?

**Comment by NikoKrause** [comment]
1-15 seconds? I can't think of a scenario where I need much more. Or maybe 1-30 seconds?

**Comment by rjanja** [comment]
Hi,

I took a first pass at this while adding support for Cinnamon 3.6 in 774c60a420a785c94a68cfdb9a272d9eed3efb80. The slider moves freely between "off" and 10 seconds. A longer duration can be set in the applet's settings if desired.

Cheers!

![cinnamon-screenshot](https://user-images.githubusercontent.com/164802/34395882-23176db0-eb19-11e7-976f-7fc483b589b9.png)
